In [30]:
import numpy as np
import pandas as pd
a = np.array([[0.1, 0.2, 3],
              [1, 2, 3]])

b = np.array([[1],
              [2],
              [3]])
c = np.array([[0.1, 0.2, 3],
              [1.1, 2.3, 3.1]])
print((a - c) ** 2)
print(np.dot(a, b))
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
print(sigmoid(np.dot(a, b)))

def softmax(y_hat: np.ndarray):
    exp_sum = 0
    exp_list = []
    softmax_list = np.ones_like(y_hat)
    example_num = y_hat.shape[0]
    label_num = y_hat.shape[1]
    for i in range(example_num):
        for j in range(label_num):
            exp_sum += np.exp(y_hat[i, j])
            exp_list.append(np.exp(y_hat[i, j]))
        for j in range(label_num):
            softmax_list[i, j] = (exp_list[j] / exp_sum)
        exp_sum = 0
        exp_list = []
    return softmax_list
print(softmax(a))

[[0.   0.   0.  ]
 [0.01 0.09 0.01]]
[[ 9.5]
 [14. ]]
[[0.99992515]
 [0.99999917]]
[[0.04931133 0.05449744 0.89619123]
 [0.09003057 0.24472847 0.66524096]]


In [37]:
import torch
def softmax(y_hat: np.ndarray):
    exp_sum = 0
    exp_list = []
    softmax_list = np.ones_like(y_hat)
    example_num = y_hat.shape[0]
    label_num = y_hat.shape[1]
    for i in range(example_num):
        for j in range(label_num):
            exp_sum += np.exp(y_hat[i, j])
            exp_list.append(np.exp(y_hat[i, j]))
        for j in range(label_num):
            softmax_list[i, j] = (exp_list[j] / exp_sum)
        exp_sum = 0
        exp_list = []
    return softmax_list
